package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "training_data_wrong_size",
    srcs = [
        # 768x250, not 768x256.
        "0-0013312-250.png",
    ],
)