package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "split-1",
    srcs = glob(["split-1/0-*.png"]),
)

filegroup(
    name = "split-2",
    srcs = glob(["split-2/0-*.png"]),
)

filegroup(
    name = "split-3",
    srcs = glob(["split-3/0-*.png"]),
)