package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "corpus_data_split_0",
    srcs = glob([
        "0-*.png"
    ]),
)