package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "fonts",
    srcs = glob(["*.otf"]),
)

filegroup(
    name = "expected_predictions",
    srcs = glob(["predicted*.png"]),
)
