package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "fonts",
    srcs = glob(["*.otf"]),
)

filegroup(
    name = "expected_predictions",
    srcs = [
        "predicted-2CF56.png",
        "predicted-653E.png",
    ],
) 