package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

exports_files([
    "LICENSE",
])

filegroup(
    name = "fonts",
    srcs = glob(["*.otf"]),
)

filegroup(
    name = "expected_predictions",
    srcs = [
        "predicted-175276.png",
    ],
) 

filegroup(
    name = "expected_training_data",
    srcs = [
        "0-0013334.png",
    ],
)