name: Lint
on: push
jobs:
  autopep8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: autopep8
        # Prints a diff if autopep8 wants to make changes. Not so aggressive as to propose a PR, though.
        run: |
          python3 -m pip install --upgrade autopep8
          python3 -m autopep8 --exit-code --diff --recursive --aggressive --aggressive .
